In [1]:
#import numpy as np
#arr_2d = np.arange(0,50).reshape(5, 10)
#print(arr_2d)
#print(arr_2d[1:3, 3:5])
# outputs:
# [[13 14]
# [23 24]]

import pandas as pd
import numpy as np

print(np.zeros(10))

print(np.ones(10))

myArr = []
for i in range(0,10):
  myArr.append(i)
print(myArr)
# [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

myArr = []
for i in range(0,10):
  myArr.append(5)
print(type(np.array(myArr)))

myArr = []
for i in range(10,51):
  myArr.append(i)
print(myArr)

print(type(np.arange(0,10)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'numpy.ndarray'>
[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]
<class 'numpy.ndarray'>


In [2]:
np.arange(0, 50)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [3]:
arr = np.arange(0,50)
arr = arr[arr % 2 == 0]
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [4]:
arr = np.arange(0, 9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
arr = np.random.rand(1)
rdm

NameError: name 'rdm' is not defined

In [ ]:
arr = np.random.randn(5, 5)
arr

In [ ]:
arr = np.linspace(0.1, 1, 100).reshape(10, 10)
arr

In [ ]:
arr = np.linspace(0, 1, 20) 
arr

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat

In [ ]:
mat = mat[2:,1:]
mat

In [ ]:
mat = mat[]
mat